# SwiftLint Configuration for tiler

# 除外パス
excluded:
  - .build
  - Package.swift

# 無効化するルール
disabled_rules:
  - trailing_whitespace  # SwiftFormat が処理
  - line_length          # 一旦緩めに

# 有効化するオプトインルール
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - discouraged_optional_boolean
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# カスタム設定
identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - x
    - y
    - w
    - h

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

# レポーター
reporter: xcode
